class Adiyogi{  
public static void main(String a[]) throws InterruptedException{
Thread.sleep(100);
System.out.println("%                                  //.      @@@@     @  &    @/ @@@                                 ");
Thread.sleep(100);
System.out.println("                                 @@      # @@@       @@@@@@@#   @@@@                                ");
Thread.sleep(100);
System.out.println("                                 @@@@@@@@@@ @@@@    #@@@@@@@@    @@@@                               ");
Thread.sleep(100);
System.out.println("                         *@@@%#@( @@@@@@@@@@@@@@.     @@@@@@@  @.   #@                              ");
Thread.sleep(100);
System.out.println("                        @@@.       @@@@@@@@@@@@  ,      @@@@@@         @                            ");
Thread.sleep(100);
System.out.println("                        @@@@@@       (@@@@@@@@ .@@,        @@@&  @@@@   @@@                         ");
Thread.sleep(100);
System.out.println("                       ,@@@@@@@@@@,@@@@@@@@@@@ @@@@           /@@@@@@@@  @@@@@@.                    ");
Thread.sleep(100);
System.out.println("                       @@@@@@@@@@@@@@@@@@@@@@@  .*                @@@@  @@ @@@@@@@@@@               ");
Thread.sleep(100);
System.out.println("                     @@@@@@@@@@@@@@@@@@@@@@@        @@@@@@@@@@      @@@@@@                          ");
Thread.sleep(100);
System.out.println("                    &@@@@@@@@@@@@@@@@@@@@@@@@@@    @@@@@@@@@@@@@@    @@@@(   @                      ");
Thread.sleep(100);
System.out.println(".                   @@@@@@@@@@@  .@@@@@ &   @@@@  @@@@%,    &  * .@*  @@@@                          ");
Thread.sleep(100);
System.out.println(".                    @@@@@@@@@ @@@@@@@@@@@@@@@@@  @@@@          @@  . @@@@@@   (                    ");
Thread.sleep(100);
System.out.println(".                    @@@@@@@@@@@@@@@@@@@@@@@@@@@  @@@@                &@@@@@     @                  ");
Thread.sleep(100);
System.out.println(".                   @@@@@@@@@@@@@@@@@@@@@@@@@@@@  @@@@                @@   @@     @                 ");
Thread.sleep(100);
System.out.println(".                   %@@@@@@@@@@@@@@@@@@@@@@         ( /                  @@@ @    @                 ");
Thread.sleep(100);
System.out.println("                    @@@@@@@@@@@@@@@@@@@@@@   @                         @ @@ @ @   @@                ");
Thread.sleep(100);
System.out.println("                  @@@@@@@@@@@@@@@@@@@@@@@@@@                          %@@ #,  @   @@@.              ");
Thread.sleep(100);
System.out.println("                 @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@               ,@(  .@@ @@@@@              ");
Thread.sleep(100);
System.out.println("                 *@@@@@@@@@@@@@@@@@@@@@@@@%             @@@           #,@ (  @@@  @@@@              ");
Thread.sleep(100);
System.out.println("                @@@@@@@@@@@@@@@@@@@@@@    @@@@                          @    @    @@@@              ");
Thread.sleep(100);
System.out.println("               @@@@@@@@@@ @@@@@@@@@@@@@@@@@@@@@@@@                          @     @@@@@             ");
Thread.sleep(100);
System.out.println("               @@@@@@@@&@@@@@@@@@@@@@@@@@@@@@@#                      @  .% @@/    @@@@@@            ");
Thread.sleep(100);
System.out.println("                @@@@@@ @@@@ @@@@@@@@@@@@@@@@                         @*@@@@ @@    @@@@@@@           ");
Thread.sleep(100);
System.out.println("                @@@@@@ @@@@ @@@@@@@@@@@@@@@                      &  @@ @@@@ %@@   @@@@@@@(          ");
Thread.sleep(100);
System.out.println("                @@@@@@      @@@@@                      @@@@@@%    .@@@@     @@@   @@@@@@@*          ");
Thread.sleep(100);
System.out.println("                 /@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ @@@@@@@@@@@    @@@@@@&           ");
Thread.sleep(100);
System.out.println("                 @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@   @@@@@@@@@.      @@@@@@@           ");
Thread.sleep(100);
System.out.println("            @      @@@     @@%@@@@@@@@@@@@@@#          @          @@@@@@@@@@@.     ,@               ");
Thread.sleep(100);
System.out.println("            @      #        @@@@@@@@     @@@                    @ @@@@@@@@@@@@       @    &         ");
Thread.sleep(100);
System.out.println("             .     @ @      @@@@@@                              @ #@@@@@@@@@@@              ,@      ");
Thread.sleep(100);
System.out.println("              /    @ @     @@@@@@                                @ @@@@@@@@@@@@                @    ");
Thread.sleep(100);
System.out.println("            &@@@   ( @   #@@@@@@@                                @@ @@@@@@@@@@@/      @@@@@@   &    ");
Thread.sleep(100);
System.out.println("           @@@@@@@   (  @@@@@@@@@@@         %                     .@@@@@@@@@@@@@/      @@@@@@@@@    ");
Thread.sleep(100);
System.out.println("       @@@@@@@@@@@   / ,@@@@@@@@@@@@         @@        .            @@@@@@@@@@@@@@       @@@@@@     ");
Thread.sleep(100);
System.out.println("     @@@@@@@@@@@@@@  % @@@@@@@@ %@@@@@       @@@      #@            @@@@@@@@@@@@@@@@          @@    ");
Thread.sleep(100);
System.out.println("     @@@@@@@@@@@@@@    */@@     @@@@@@@@@     @@*    @@#          @@@@#@   (@@@@@(@@@@@/         *& ");
Thread.sleep(100);
System.out.println("      @@@@@@@@@@@@@@@  @@@      @@@@@@@@@@@@@%(@  /@@@@@@@@@@@@@@@@@ @/ @  @@@@@       .@@@@@&@   @ ");
Thread.sleep(100);
System.out.println("   (@@@@@@@@@@@@@@@@@@@@@@    @@     @@@@@@@@@@@@@@@@@@@@@@@@@@, #@@@   %  @@@@@                 @@ ");
Thread.sleep(100);
System.out.println(" @@@@@@&   @@@@@@@@@@@@@@@  %  /@@@@@        @@@@@@@@@@@ ( * @@@@@@  @@#@ @@@@                      ");
Thread.sleep(100);
System.out.println("@@     @@@@@@@@@@@@@@@@@@@@@  @@  @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  @@@@ @@@                         ");
Thread.sleep(100);
System.out.println("     @@@@@@@ @@@@@@@@@@@@@@@@@%( @%.  @@@@@@@@@@@@@@@@@@@@@@@   @@@@@  @*                           ");
Thread.sleep(100);
System.out.println("   @@@&   @@@@@@@@@@@@@@@@@@@@@@@@@  @@@  @@@@@@@@@@@@@@@ %  @@& @ @@@ %&@@@@@@@@@@&                ");
Thread.sleep(100);
System.out.println("/     @@@@@(                     @@@@@@   @@@@      @ @@@@@  @@@@@@@@@@@@@@@           @     *      ");
Thread.sleep(100);
System.out.println("    @#                                 @@@@@@**     @ @ &@@@@@@@@@@@@@#        .  .@     .          ");
Thread.sleep(100);
System.out.println("                                             (@@@@@@@@@@@@@@@@@@@@             .                    ");
Thread.sleep(100);
System.out.println("                                                    &@@@@@&                                         ");
Thread.sleep(100);
System.out.println("");
Thread.sleep(100);
System.out.println("	    :::     ::::::::: ::::::::::: :::   :::  ::::::::   :::::::: ::::::::::: ");
System.out.println("	  :+: :+:   :+:    :+:    :+:     :+:   :+: :+:    :+: :+:    :+:    :+:     ");
System.out.println("	 +:+   +:+  +:+    +:+    +:+      +:+ +:+  +:+    +:+ +:+           +:+     ");
System.out.println("	+#++:++#++: +#+    +:+    +#+       +#++:   +#+    +:+ :#:           +#+     ");
System.out.println("	+#+     +#+ +#+    +#+    +#+        +#+    +#+    +#+ +#+   +#+#    +#+     ");
System.out.println("	#+#     #+# #+#    #+#    #+#        #+#    #+#    #+# #+#    #+#    #+#     ");
System.out.println("	###     ### ######### ###########    ###     ########   ######## ########### ");



}
}